name: Terraform CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
      - run: terraform plan
